baseURL: 'https://ko-sinus.github.io'
languageCode: 'en-us'
title: 'Koji Andria'
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: projects
      name: Projects
      title: Projects posts
      url: /projects
      weight: 1
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Koji Andria"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Koji Andria" # Brand name for the brand | default is the title variable
    disableSearch: true
    # searchPlaceholder: "Search"
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: true
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Koji."
    subtitle: "I build tools to fix bodies"
    # content: "I'm a `Hardware Research Engineer` in the medical field. My main interests lie in cross-disciplinary fields such as `Human-Computer Interaction` and `Human-Centered Computing`."
    content: "I'm a `Hardware Systems Engineer` in the medical field. My main interests lie in cross-disciplinary fields such as `Human-Computer Interaction` and `Human-Centered Computing`."
    image: /images/avatar.jpg
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "/pdfs/ResumeEN.pdf"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/ko-sinus
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/koji-andria/lang?=ENG
      # customIcons:
        - icon: fas fa-envelope
          url: mailto:koji.andria@e.email

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/avatar.png"
    content: |-
      I'm a French engineer. Voilà.

      I am interested in `human-centered initiatives` that can improve day-to-day life.
      With a strong emphasis on the healthcare field, most of my projects consist in `investigating anthropometrics` in order to `interact with data in a more tangible and physical way`. You can find <a href="#projects">some of them here on this website</a>.

      Reality is I spend most of my time drinking coffee.

      My background lies in hardware systems engineering.
      My professional experiences mostly relate to the healthcare industry, covering both the patient and the physician's concerns - including `bio-sensing` techniques, `clinical decision support` systems or `assistive technologies`.
    # My professional experiences mostly relate to the healthcare industry, covering both the patient and the physician's concerns - including `bio-sensing` technologies, `computational physiology`, `digital twin` modeling, `clinical decision-support systems` or `assistive technologies`.
    
    # skills:
    #   enable: true
    #   title: "Here are a few technologies I've been working with recently:"
    #   items:
    #     - "HTML"
    #     - "CSS"
    #     - "JavaScript"
    #     - "React"
    #     - "Node"
    #     - "Express"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      # - job: "Research Scientist"
      - job: "Hardware Systems Engineer"
        company: "Stella Surgical"
        companyUrl: "https://stellasurgical.com/en/home-page/"
        date: "January 2022 - present"
        # featuredLink:
        #   enable: true
        #   url: "https://example.com"
        # info:
        #   enable: true
        #   content: Stella Surgical is a French startup in the organ transplantation field.
        # content: |
        #   I am currently working as a research scientist at Stella Surgical, as part of a Ph.D fellowship.

        #   - Conceived a new type of graft preservation and bio-sensing analysis device for organ transplants.
        #   - Digital twin modeling of living organs for clinical decision making and logistic optimisation during organ transplant processes.

        #   Prior to this role, I worked as a hardware systems engineer for more than a year. I was mainly responsible of embedded systems integration and development.
        content: |
          I am currently working as a hardware systems engineer.
            - Responsible of embedded systems and hardware product development.
            - Contributed on process modelling, sensors integration and medical regulatory requirements.

      - job: "Hardware Research Engineer"
        company: "LIRMM"
        companyUrl: "https://www.lirmm.fr/lirmm-en/"
        date: "September 2021 - January 2022"
        info:
          enable: true
          content: LIRMM stands for Laboratory of Computer Science, Robotics and Microelectronics of Montpellier
        # featuredLink:
        #   enable: true
        #   url: "https://example.com"
        content: |
          I led a personal research initiative, which was about hand gesture recognition and bio-sensing for sign language interpretation.
          
            - Worked on hardware architecture definition
            - MCAD/ECAD rapid prototyping
            - Signal processing & firmware programming.

      - job: "Assistive Technology Designer"
        company: "HumanLab Saint-Pierre"
        companyUrl: "https://www.humanlabsaintpierre.org/"
        date: "January 2021 - July 2021"
        info:
          enable: false
          # content: HumanLabs consist of Fablabs that are specifically dedicated to assistive technology.
        featuredLink:
          enable: true
          name: View the project
          url: "https://www.youtube.com/watch?v=PhL7JxOnTew"
        content: |
          I worked closely with a medical team (occupational therapists, ortho-prosthetists, doctors) from the Institut Saint-Pierre (paediatric hospital).
            - Developed an assistive robotic orthosis for children.
            - Designed hardware assistive technologies using rapid-prototyping techniques with end-users.

      - job: "Research Intern"
        company: "TU Delft"
        companyUrl: "https://www.tudelft.nl/en/"
        date: "May 2020 - August 2020"
        info:
          enable: false
        featuredLink:
          enable: false
          name: View the paper
          url: "https://example.com"
        content: |
          Ethical Decision Making for autonomous systems considering moral uncertainty.
            - Computational modelling of ethical theories
            - Applied data-analysis techniques on [MIT’s moral machine dilemma dataset](https://www.moralmachine.net/)
            - Modelled a decision-making mechanism rooted in normative ethics to incorporate moral uncertainty on the field of autonomous vehicles.

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      # - title: "Ph.D in Robotics and Microelectronic Systems"
      #   school:
      #     name: "Université de Montpellier, France"
      #     url: "https://www.umontpellier.fr/en/"
      #   date: "2022 - present"
      - title: "Master of Science in Digital Health"
        school:
          name: "Université de Montpellier, France"
          url: "https://www.umontpellier.fr/en/"
        date: "2022"
        # GPA:
        content: |-
          Major:
            Health Devices Engineering 
          
           - Rank : 1st out of 22

      - title: "Diplôme d'Ingénieur (M.Eng) in Systems Engineering"
        school:
          name: "École des Mines d'Alès, France"
          url: "https://www.imt-mines-ales.fr/en"
        date: "2022"
        content: |-
          Major:
            Mechatronics
          
          Extracurricular Activities
            - Organised the first TEDx edition in Alès, Gard, France.
            - Active volunteer in campus' Culture, Arts and Music Organising Comitee.
        # featuredLink:
        #   enable: true
        #   name: "My academic record"
        #   url: "https://example.com"

  # Achievements
  achievements:
    enable: true
    # title: "Custom Name"
    items:
      - title: TEDx Licensee
        content: Organised the first TEDx edition in Alès, Gard, France.
        url: https://www.ted.com/tedx/events/35162
      - title: Arts Conservatory
        content: Graduated in jazz, classical and electroacoustic music.

  # projects
  projects:
    enable: false
    # title: "Custom Name"
    # items:
    #   - title: Hugo Profile
    #     content: A highly customizable and mobile first Hugo template for personal portfolio and blog.
    #     image: /images/projects/profile.png
    #     featured:
    #       name: Demo
    #       link: https://hugo-profile.netlify.app
    #     badges:
    #       - "Hugo"
    #       - "Bootstrap"
    #       - "Javascript"
    #     links:
    #       - icon: fa fa-envelope
    #         url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
    #       - icon: fab fa-github
    #         url: https://github.com/gurusabarish/hugo-profile
    #       - icon: fab fa-twitter
    #         url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

    #   - title: Image Converter
    #     content: A web app to convert image to pdf, png to jpg, png to jpg and png to webp without database using django.
    #     image: /images/projects/converter.jpg
    #     featured:
    #       name: Demo
    #       link: https://django-converter.herokuapp.com
    #     badges:
    #       - "Django"
    #       - "Bootstrap"
    #     links:
    #       - icon: fab fa-github
    #         url: https://github.com/gurusabarish/converter

    #   - title: Hugo Profile V2
    #     content: A clean and simple Hugo template for personal portfolio and blog.
    #     image: /images/projects/profile2.jpg
    #     featured:
    #       name: Demo V2
    #       link: https://hugo-profile-2.netlify.app
    #     badges:
    #       - "Hugo"
    #       - "Bootstrap"
    #       - "Javascript"
    #     links:
    #       - icon: fab fa-github
    #         url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Please do not hesitate to say hi!
    email: koji.andria@e.email
    btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "projects"
      count: 3
      title: Recent Projects
      enable: false
      disableFeaturedImage: false
    # socialNetworks:
    #   github: https://github.com
    #   linkedin: https://linkedin.com
    #   twitter: https://twitter.com
    #   instagram: https://instagram.com
    #   facebook: https://facebook.com

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"
