baseURL: 'https://ko-sinus.github.io'
languageCode: 'en-us'
title: 'Koji Andria'
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: projects
      name: Projects
      title: Projects posts
      url: /projects
      weight: 1

params:
  title: "Koji Andria"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: "js"

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  color:
    textColor: black
    secondaryTextColor: '#54BAB9'
    backgroundColor: '#FBF8F1'
    secondaryBackgroundColor: '#fff'
    primaryColor: '#54BAB9'
    secondaryColor: white

    darkmode:
      textColor: '#DDE6ED'
      secondaryTextColor: grey
      backgroundColor: '#27374D'
      secondaryBackgroundColor: '#27374D'
      primaryColor: '#DDE6ED'
      secondaryColor: 

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    brandName: "Koji Andria" # Brand name for the brand | default is the title variable
    disableSearch: true
    # searchPlaceholder: "Search"
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: true
      disableAchievements: true
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Koji."
    subtitle: "I build healthcare toolkits"
    content: "I'm a `Hardware Research Engineer` in the medical field. My main interests lie in cross-disciplinary fields such as 
      `Bio-sensing` and `Computational Physiology`."
    image: /images/avatar.jpg
    bottomImage:
      enable: true
    button:
      enable: true
      name: "Resume"
      url: "/pdfs/CV_KojiAndria.pdf"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/koji-andria/lang?=ENG
        - icon: fas fa-envelope
          url: mailto:koji.andria@e.email
        - icon: fab fa-researchgate
          url: https://www.researchgate.net/profile/Koji-Andriamahery
        # - icon: fab fa-github
        #   url: https://github.com/ko-sinus

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/avatar_round.png"
    content: |-
      I'm a French engineer. Voilà.

      I am interested in `human-centered initiatives` that can improve day-to-day life.
      I believe in a technology that fits and adapts to our needs, as we unfortunately too often observe individuals adapting themself to technology.
      With a strong emphasis on the healthcare field, most of my projects consist in `investigating anthropometrics` -
      whether to help physicians make decision or patients move their bodies, but over all, to blink a LED.
      You can find <a href="/projects">some of them here on this website</a>.

      Reality is I spend most of my time drinking coffee.

      My background lies in hardware systems engineering.
      My professional experiences mostly relate to the medical industry and include topics such as 
      `bio-sensing` techniques, `clinical decision support` systems or `assistive technologies`.
    
  # Experience
  experience:
    enable: true
    title: "Work Experience"
    items:
      - job: "Research Engineer - Hardware, Data"
        company: "Stella Surgical"
        companyUrl: "https://stellasurgical.com/en/home-page/"
        date: "January 2022 - present"
        info:
          enable: true
          content: Prior to this role, I worked as a systems engineer for more than a year
        content: |
          I am currently working as a research engineer at Stella Surgical, as part of an industrial Ph.D fellowship.

          - Contributed to new types of physiological data analysis techniques for liver grafts.
          - Worked on clinical process modeling and decision support systems for medical transplant teams.
          - Led technical faisability studies on R&D early-stage projects, including medical regulatory requirements for both software and hardware.

          Prior to this role, I served the company as a hardware systems engineer for more than a year. I was mainly responsible of embedded systems integration and product development.

      - job: "Hardware/Firmware Engineer"
        company: "LIRMM"
        companyUrl: "https://www.lirmm.fr/lirmm-en/"
        date: "September 2021 - January 2022"
        info:
          enable: true
          content: LIRMM stands for Laboratory of Computer Science, Robotics and Microelectronics of Montpellier
        # featuredLink:
        #   enable: true
        #   url: "https://example.com"
        content: |
          Led a personal research initiative, which was about embedded hand gesture recognition and bio-sensing for sign language interpretation.
          
            - Worked on hardware architecture definition.
            - MCAD/ECAD rapid prototyping.
            - Signal processing & firmware programming.

      - job: "Assistive Technology Designer"
        company: "HumanLab Saint-Pierre"
        companyUrl: "https://www.humanlabsaintpierre.org/"
        date: "January 2021 - July 2021"
        info:
          enable: false
          # content: HumanLabs consist of Fablabs that are specifically dedicated to assistive technology.
        featuredLink:
          enable: true
          name: View the project
          url: "https://www.youtube.com/watch?v=PhL7JxOnTew"
        content: |
          Worked closely with a medical team (occupational therapists, ortho-prosthetists, doctors) from the Institut Saint-Pierre (paediatric hospital).
            - Developed an assistive robotic orthosis for children.
            - Designed hardware assistive technologies using rapid-prototyping techniques with end-users.

      - job: "Research Intern"
        company: "TU Delft"
        companyUrl: "https://www.tudelft.nl/en/"
        date: "May 2020 - August 2020"
        info:
          enable: false
        featuredLink:
          enable: true
          name: View the paper
          url: "https://www.frontiersin.org/articles/10.3389/fnrgo.2023.1147211/full"
        content: |
          Worked on ethical decision making models for autonomous systems considering moral uncertainty.
            - Computational modeling of ethical theories.
            - Applied data-analysis techniques on [MIT’s moral machine dilemma dataset](https://www.moralmachine.net/).
            - Modelled a decision-making mechanism rooted in normative ethics to incorporate moral uncertainty on the field of autonomous vehicles.

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      # - title: "Ph.D in Robotics and Microelectronic Systems"
      #   school:
      #     name: "Université de Montpellier, France"
      #     url: "https://www.umontpellier.fr/en/"
      #   date: "2023 - present"
      
      - title: "Master of Science in Digital Health"
        school:
          name: "Université de Montpellier, France"
          url: "https://www.umontpellier.fr/en/"
        date: "2022"
        content: |-
          Major:
            Health Devices Engineering 
          
           - Ranked 1st

      - title: "Diplôme d'Ingénieur (M.Eng) in Systems Engineering"
        school:
          name: "École des Mines d'Alès, France"
          url: "https://www.imt-mines-ales.fr/en"
        date: "2022"
        content: |-
          Major:
            Mechatronics

            - Organised the first TEDx edition in Alès, Gard, France.
            - Active volunteer in campus' Culture, Arts and Music Organising Comitee.

  # Achievements
  achievements:
    enable: true
    title: "Projects"
    items:
      # - title: TEDx Licensee
      #   content: Organised the first TEDx edition in Alès, Gard, France.
      #   url: https://www.ted.com/tedx/events/35162
      # - title: Arts Conservatory
      #   content: Graduated in jazz, classical and electroacoustic music.
      - title: Some of the things I've worked on
        content: documented here when I find some time to.
        url: /projects

   # projects
  projects:
    enable: false
    

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Please do not hesitate to say hi!
    email: koji.andria@e.email
    btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "projects"
      count: 3
      title: Recent Projects
      enable: false
      disableFeaturedImage: false
    socialNetworks:
      linkedin: https://www.linkedin.com/in/koji-andria/lang?=ENG
      # github: https://github.com/ko-sinus
      email: mailto:koji.andria@e.email
      researchgate: https://www.researchgate.net/profile/Koji-Andriamahery

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this project"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: true
  twitter:
    disable: true
  vimeo:
    disable: true
  youtube:
    disable: true